spring.datasource.url=jdbc:postgresql://localhost:5432/puerto_db
spring.datasource.username=postgres
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update
spring.application.name=Puerto
